// Notebook Modal
export const NOTEBOOK_OPENMODAL = 'NOTEBOOK_OPENMODAL'
export const NOTEBOOK_CLOSEMODAL = 'NOTEBOOK_CLOSEMODAL'
export const NOTEBOOK_UPDATE_STATE = 'NOTEBOOK_UPDATE_STATE'

// Notebook List
export const FETCHNOTEBOOKLIST = ' FETCHNOTEBOOKLIST'
export const ADDNOTEBOOKLIST = 'ADDNOTEBOOKLIST'
export const UPDATENOTEBOOKLIST = 'UPDATENOTEBOOKLIST'